<?php
/* ============================================================
 * Clarity Theme for ISPConfig — brand.php  (the brand READER)
 * ------------------------------------------------------------
 * Emits a small stylesheet that realizes the neutral, theme-
 * agnostic "brand-token contract" as Clarity --nz-* overrides.
 * Any customizer (e.g. ispconfig-customizer) WRITES the contract
 * into ISPConfig's sys_ini table; this file READS it. The two
 * are decoupled — they share only the DB keys documented in the
 * README ("Brand-token contract"), never code.
 *
 * Contract consumed (sys_ini, global row sysini_id = 1):
 *   custom_logo  column           -> logo (data URI), via CSS content:
 *   config [branding] accent_hex  -> re-hues the blue ramp + accents
 *   config [branding] rail_hex    -> the navy brand rail
 *   config [branding] login_bg    -> login-screen background base
 *   config [branding] show_ispconfig_credit (0/1) -> footer courtesy line
 *   config [branding] show_theme_credit     (0/1) -> footer courtesy line
 *
 * Design constraints:
 *   - Pre-auth safe: the login screen links this file, so it must
 *     work with no session. It does a single, side-effect-free,
 *     read-only query of one sys_ini row (no ISPConfig app bootstrap,
 *     no maintenance-mode redirects, no session start).
 *   - Always HTTP 200 with valid CSS. When nothing is set it emits an
 *     empty sheet and the theme falls back to its shipped tokens/logo —
 *     so it is a no-op both without the customizer and before first use.
 *   - Injection-safe: every value is validated (hex regex / data-URI
 *     regex / 0|1) before it reaches the output.
 * ============================================================ */

header('Content-Type: text/css; charset=utf-8');

/* ---- read the contract (direct, minimal, side-effect-free) ---- */
$branding    = array();
$custom_logo = '';

$config_inc = __DIR__ . '/../../../lib/config.inc.php'; // interface/lib/config.inc.php
if (is_readable($config_inc)) {
    // config.inc.php only defines $conf + constants — but on a web request it also
    // emits `Content-Type: text/html`, which we re-assert away from below.
    require $config_inc;
    if (isset($conf) && is_array($conf) && !empty($conf['db_host'])) {
        // PHP 8.1+ makes mysqli throw by default; keep the graceful errno idiom working.
        if (function_exists('mysqli_report')) {
            mysqli_report(MYSQLI_REPORT_OFF);
        }
        try {
            $port   = isset($conf['db_port']) ? (int)$conf['db_port'] : 3306;
            $mysqli = @new mysqli($conf['db_host'], $conf['db_user'], $conf['db_password'], $conf['db_database'], $port);
            if ($mysqli && !$mysqli->connect_errno) {
                @$mysqli->set_charset('utf8mb4');
                if ($res = @$mysqli->query('SELECT config, custom_logo FROM sys_ini WHERE sysini_id = 1')) {
                    if ($row = $res->fetch_assoc()) {
                        $branding    = brand_parse_ini_section((string)$row['config'], 'branding');
                        $custom_logo = (string)$row['custom_logo'];
                    }
                }
                if ($mysqli instanceof mysqli) {
                    $mysqli->close();
                }
            }
        } catch (\Throwable $e) {
            // any DB fault -> emit empty CSS; never leak an error on this pre-auth route
            $branding    = array();
            $custom_logo = '';
        }
    }
}

// Re-assert the stylesheet MIME: config.inc.php sends text/html on web requests,
// and browsers reject a standards-mode stylesheet whose type isn't text/css.
header('Content-Type: text/css; charset=utf-8');

/* ---- revalidation: cheap ETag so accent/logo changes bust cache ---- */
$etag = '"' . md5(serialize($branding) . '|' . md5($custom_logo)) . '"';
header('ETag: ' . $etag);
// Cache briefly so this isn't a blocking round-trip on every full page load;
// the branding is global (same for everyone), and a saved change appears within
// max-age or on a hard refresh (Ctrl+Shift+R).
header('Cache-Control: public, max-age=60');
if (isset($_SERVER['HTTP_IF_NONE_MATCH']) && trim($_SERVER['HTTP_IF_NONE_MATCH']) === $etag) {
    http_response_code(304);
    exit;
}

/* ---- resolve + validate the contract values ---- */
$accent   = brand_hex($branding, 'accent_hex');
$rail     = brand_hex($branding, 'rail_hex');
$login_bg = brand_hex($branding, 'login_bg');

$show_ispc  = !(isset($branding['show_ispconfig_credit']) && $branding['show_ispconfig_credit'] === '0');
$show_theme = !(isset($branding['show_theme_credit'])     && $branding['show_theme_credit']     === '0');

$css = "/* Clarity brand overrides — generated by themes/clarity/brand.php */\n";

/* ---- accent: re-hue the blue ramp onto Clarity's tuned L ladder ---- */
if ($accent !== '') {
    // Clarity's blue ramp lightness ladder (H,S taken from the brand accent).
    $ladder = array(
        100 => 87, 200 => 78, 300 => 70, 400 => 59, 500 => 48,
        600 => 40, 700 => 34, 800 => 27, 900 => 21, 1000 => 15,
    );
    $root = '';
    foreach ($ladder as $step => $l) {
        $root .= sprintf("  --nz-blue-%d: %s;\n", $step, brand_shade($accent, $l));
    }

    // The rgba literals that carry the hue (tokens.css lines ~114-149).
    // Dark scope uses the bright accent (blue-400 role); light uses the base (blue-700 role).
    $bright = brand_shade($accent, 59); // ~ blue-400
    $base   = brand_shade($accent, 34); // ~ blue-700

    if ($rail !== '') {
        $root .= "  --nz-rail: {$rail};\n";
        $root .= '  --nz-rail-active: ' . brand_shade($rail, 15) . ";\n";
    }
    $root .= '  --nz-focus-ring: '   . brand_rgba($bright, 0.40) . ";\n";
    $root .= '  --nz-selection-bg: ' . brand_rgba($bright, 0.35) . ";\n";
    $root .= '  --nz-row-hover: '    . brand_rgba($bright, 0.045) . ";\n";
    $root .= '  --nz-accent-edge: '  . brand_rgba($bright, 0.45) . ";\n";
    $root .= '  --nz-info-edge: '    . brand_rgba($bright, 0.35) . ";\n";
    $root .= '  --nz-info-tint: '    . brand_rgba($bright, 0.10) . ";\n";
    $root .= '  --nz-pulse-ring: '   . brand_rgba($bright, 0.45) . ";\n";
    $css  .= ":root {\n{$root}}\n";

    // Light scope redeclares the same literals + a few selection tints.
    $light  = '';
    $light .= '  --nz-focus-ring: '     . brand_rgba($base, 0.45) . ";\n";
    $light .= '  --nz-selection-bg: '   . brand_shade($accent, 82) . ";\n";
    $light .= '  --nz-selected: '       . brand_shade($accent, 93) . ";\n";
    $light .= '  --nz-selected-strong: ' . brand_shade($accent, 88) . ";\n";
    $light .= '  --nz-row-hover: '      . brand_rgba($base, 0.05) . ";\n";
    $light .= '  --nz-accent-edge: '    . brand_rgba($base, 0.40) . ";\n";
    $light .= '  --nz-info-edge: '      . brand_rgba($base, 0.30) . ";\n";
    $light .= '  --nz-info-tint: '      . brand_rgba($base, 0.08) . ";\n";
    $light .= '  --nz-pulse-ring: '     . brand_rgba($base, 0.40) . ";\n";
    // light info-alert surface is a hardcoded pale-blue literal in tokens.css — re-hue it too
    $light .= '  --nz-info-surface: '   . brand_shade($accent, 94) . ";\n";
    $css   .= ":root[data-nz-theme='light'] {\n{$light}}\n";
} elseif ($rail !== '') {
    // rail set without an accent — just the navy band
    $css .= ":root {\n  --nz-rail: {$rail};\n  --nz-rail-active: " . brand_shade($rail, 15) . ";\n}\n";
}

/* ---- login background ---- */
if ($accent !== '' || $login_bg !== '') {
    $g1   = $accent !== '' ? brand_shade($accent, 34) : '#0065AB';
    $g2   = $accent !== '' ? brand_shade($accent, 48) : '#0090F5';
    $base = $login_bg !== '' ? $login_bg : 'var(--nz-page)';
    $css .= "body.nz-login {\n  background:\n" .
            '    radial-gradient(640px 420px at 50% -8%, ' . brand_rgba($g1, 0.38) . ", transparent 68%),\n" .
            '    radial-gradient(900px 600px at 88% 112%, ' . brand_rgba($g2, 0.10) . ", transparent 60%),\n" .
            "    {$base};\n}\n";
    $css .= ":root[data-nz-theme='light'] body.nz-login {\n  background:\n" .
            '    radial-gradient(640px 420px at 50% -8%, ' . brand_rgba($g1, 0.14) . ", transparent 68%),\n" .
            '    radial-gradient(900px 600px at 88% 112%, ' . brand_rgba($g2, 0.05) . ", transparent 60%),\n" .
            "    {$base};\n}\n";
}

/* ---- logo: override the shipped wordmark with the host's custom_logo ---- */
if ($custom_logo !== '' && preg_match('#^data:image/[a-z0-9.+-]+;base64,[A-Za-z0-9+/=]+$#i', $custom_logo)) {
    // both dimensions auto + a max box -> the logo keeps its aspect ratio and fits,
    // for any width (the base rules pin a fixed height, which would distort wide logos).
    $css .= "#logo img { content: url(\"{$custom_logo}\"); height: auto; width: auto; max-height: 26px; max-width: 180px; }\n";
    $css .= ".nz-topbar-brand img { content: url(\"{$custom_logo}\"); height: auto; width: auto; max-height: 18px; max-width: 120px; }\n";
    $css .= ".nzl-brand img { content: url(\"{$custom_logo}\"); height: auto; width: auto; max-height: 36px; max-width: 100%; }\n";
}

/* ---- attribution courtesy lines (source license notices are untouched) ---- */
if (!$show_ispc)  { $css .= ".nz-credit-ispconfig { display: none; }\n"; }
if (!$show_theme) { $css .= ".nz-credit-theme { display: none; }\n"; }

echo $css;

/* ============================================================
 * Helpers — pure, dependency-free.
 * ============================================================ */

/** Extract one INI section's scalar key/values, robust to the rest of the blob. */
function brand_parse_ini_section($config, $section)
{
    $out = array();
    $pattern = '/^\[' . preg_quote($section, '/') . '\]\s*$(.*?)(?=^\[|\z)/ms';
    if (!preg_match($pattern, $config, $m)) {
        return $out;
    }
    foreach (preg_split('/\r?\n/', $m[1]) as $line) {
        if (preg_match('/^\s*([A-Za-z0-9_]+)\s*=\s*(.*?)\s*$/', $line, $kv)) {
            $out[strtolower($kv[1])] = $kv[2];
        }
    }
    return $out;
}

/** Return a validated #rrggbb value from the branding array, or '' if absent/invalid. */
function brand_hex($branding, $key)
{
    if (isset($branding[$key]) && preg_match('/^#[0-9A-Fa-f]{6}$/', $branding[$key])) {
        return $branding[$key];
    }
    return '';
}

/** Keep a hex colour's hue + saturation, set its lightness to $l (0-100). Returns #rrggbb. */
function brand_shade($hex, $l)
{
    list($h, $s, ) = brand_hex_to_hsl($hex);
    return brand_hsl_to_hex($h, $s, max(0.0, min(100.0, (float)$l)));
}

/** "rgba(r, g, b, a)" from a hex colour. */
function brand_rgba($hex, $alpha)
{
    $c = ltrim($hex, '#');
    $r = hexdec(substr($c, 0, 2));
    $g = hexdec(substr($c, 2, 2));
    $b = hexdec(substr($c, 4, 2));
    return sprintf('rgba(%d, %d, %d, %s)', $r, $g, $b, rtrim(rtrim(sprintf('%.3f', $alpha), '0'), '.'));
}

/** #rrggbb -> array(h[0-360], s[0-100], l[0-100]). */
function brand_hex_to_hsl($hex)
{
    $c = ltrim($hex, '#');
    $r = hexdec(substr($c, 0, 2)) / 255;
    $g = hexdec(substr($c, 2, 2)) / 255;
    $b = hexdec(substr($c, 4, 2)) / 255;
    $max = max($r, $g, $b);
    $min = min($r, $g, $b);
    $l = ($max + $min) / 2;
    $d = $max - $min;
    if ($d == 0) {
        return array(0, 0, $l * 100);
    }
    $s = $d / (1 - abs(2 * $l - 1));
    if ($max == $r) {
        $h = 60 * fmod((($g - $b) / $d), 6);
    } elseif ($max == $g) {
        $h = 60 * ((($b - $r) / $d) + 2);
    } else {
        $h = 60 * ((($r - $g) / $d) + 4);
    }
    if ($h < 0) {
        $h += 360;
    }
    return array($h, $s * 100, $l * 100);
}

/** h[0-360], s[0-100], l[0-100] -> #rrggbb. */
function brand_hsl_to_hex($h, $s, $l)
{
    $s /= 100;
    $l /= 100;
    $c = (1 - abs(2 * $l - 1)) * $s;
    $x = $c * (1 - abs(fmod($h / 60, 2) - 1));
    $m = $l - $c / 2;
    if ($h < 60)       { $rp = $c; $gp = $x; $bp = 0; }
    elseif ($h < 120)  { $rp = $x; $gp = $c; $bp = 0; }
    elseif ($h < 180)  { $rp = 0; $gp = $c; $bp = $x; }
    elseif ($h < 240)  { $rp = 0; $gp = $x; $bp = $c; }
    elseif ($h < 300)  { $rp = $x; $gp = 0; $bp = $c; }
    else               { $rp = $c; $gp = 0; $bp = $x; }
    return sprintf('#%02X%02X%02X',
        (int)round(($rp + $m) * 255),
        (int)round(($gp + $m) * 255),
        (int)round(($bp + $m) * 255));
}
